#ifndef _ALTERA_F2SDRAM_ONLY_MASTER_H_
#define _ALTERA_F2SDRAM_ONLY_MASTER_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'f2sdram_only_master' and devices
 * connected to the following master:
 *   master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'hps_0_bridges', class 'hps_bridge_avalon'
 * The macros are prefixed with 'HPS_0_BRIDGES_'.
 * The prefix is the slave descriptor.
 */
#define HPS_0_BRIDGES_COMPONENT_TYPE hps_bridge_avalon
#define HPS_0_BRIDGES_COMPONENT_NAME hps_0_bridges
#define HPS_0_BRIDGES_BASE 0x0
#define HPS_0_BRIDGES_SPAN 0xffffffff
#define HPS_0_BRIDGES_END 0xfffffffe


#endif /* _ALTERA_F2SDRAM_ONLY_MASTER_H_ */
