#ifndef _ALTERA_FPGA_ONLY_MASTER_H_
#define _ALTERA_FPGA_ONLY_MASTER_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'fpga_only_master' and devices
 * connected to the following master:
 *   master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x1000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x1007
#define SYSID_QSYS_ID 4294906626
#define SYSID_QSYS_TIMESTAMP 1553717928

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x2000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x2007
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x3000
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x300f
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_DATA_WIDTH 2
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE FALLING
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE EDGE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x3020
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x302f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 7
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 127

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x3040
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x304f
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 1
#define DIPSW_PIO_DATA_WIDTH 4
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE ANY
#define DIPSW_PIO_FREQ 50000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE EDGE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'flags_in', class 'altera_avalon_pio'
 * The macros are prefixed with 'FLAGS_IN_'.
 * The prefix is the slave descriptor.
 */
#define FLAGS_IN_COMPONENT_TYPE altera_avalon_pio
#define FLAGS_IN_COMPONENT_NAME flags_in
#define FLAGS_IN_BASE 0x4000
#define FLAGS_IN_SPAN 16
#define FLAGS_IN_END 0x400f
#define FLAGS_IN_BIT_CLEARING_EDGE_REGISTER 0
#define FLAGS_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FLAGS_IN_CAPTURE 0
#define FLAGS_IN_DATA_WIDTH 32
#define FLAGS_IN_DO_TEST_BENCH_WIRING 0
#define FLAGS_IN_DRIVEN_SIM_VALUE 0
#define FLAGS_IN_EDGE_TYPE NONE
#define FLAGS_IN_FREQ 50000000
#define FLAGS_IN_HAS_IN 1
#define FLAGS_IN_HAS_OUT 0
#define FLAGS_IN_HAS_TRI 0
#define FLAGS_IN_IRQ_TYPE NONE
#define FLAGS_IN_RESET_VALUE 0

/*
 * Macros for device 'flags_out', class 'altera_avalon_pio'
 * The macros are prefixed with 'FLAGS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FLAGS_OUT_COMPONENT_TYPE altera_avalon_pio
#define FLAGS_OUT_COMPONENT_NAME flags_out
#define FLAGS_OUT_BASE 0x4020
#define FLAGS_OUT_SPAN 16
#define FLAGS_OUT_END 0x402f
#define FLAGS_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define FLAGS_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FLAGS_OUT_CAPTURE 0
#define FLAGS_OUT_DATA_WIDTH 32
#define FLAGS_OUT_DO_TEST_BENCH_WIRING 0
#define FLAGS_OUT_DRIVEN_SIM_VALUE 0
#define FLAGS_OUT_EDGE_TYPE NONE
#define FLAGS_OUT_FREQ 50000000
#define FLAGS_OUT_HAS_IN 0
#define FLAGS_OUT_HAS_OUT 1
#define FLAGS_OUT_HAS_TRI 0
#define FLAGS_OUT_IRQ_TYPE NONE
#define FLAGS_OUT_RESET_VALUE 0

/*
 * Macros for device 'configuration_1', class 'altera_avalon_pio'
 * The macros are prefixed with 'CONFIGURATION_1_'.
 * The prefix is the slave descriptor.
 */
#define CONFIGURATION_1_COMPONENT_TYPE altera_avalon_pio
#define CONFIGURATION_1_COMPONENT_NAME configuration_1
#define CONFIGURATION_1_BASE 0x4040
#define CONFIGURATION_1_SPAN 16
#define CONFIGURATION_1_END 0x404f
#define CONFIGURATION_1_BIT_CLEARING_EDGE_REGISTER 0
#define CONFIGURATION_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CONFIGURATION_1_CAPTURE 0
#define CONFIGURATION_1_DATA_WIDTH 32
#define CONFIGURATION_1_DO_TEST_BENCH_WIRING 0
#define CONFIGURATION_1_DRIVEN_SIM_VALUE 0
#define CONFIGURATION_1_EDGE_TYPE NONE
#define CONFIGURATION_1_FREQ 50000000
#define CONFIGURATION_1_HAS_IN 0
#define CONFIGURATION_1_HAS_OUT 1
#define CONFIGURATION_1_HAS_TRI 0
#define CONFIGURATION_1_IRQ_TYPE NONE
#define CONFIGURATION_1_RESET_VALUE 0

/*
 * Macros for device 'fans', class 'altera_avalon_pio'
 * The macros are prefixed with 'FANS_'.
 * The prefix is the slave descriptor.
 */
#define FANS_COMPONENT_TYPE altera_avalon_pio
#define FANS_COMPONENT_NAME fans
#define FANS_BASE 0x40a0
#define FANS_SPAN 16
#define FANS_END 0x40af
#define FANS_BIT_CLEARING_EDGE_REGISTER 0
#define FANS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FANS_CAPTURE 0
#define FANS_DATA_WIDTH 2
#define FANS_DO_TEST_BENCH_WIRING 0
#define FANS_DRIVEN_SIM_VALUE 0
#define FANS_EDGE_TYPE NONE
#define FANS_FREQ 50000000
#define FANS_HAS_IN 0
#define FANS_HAS_OUT 1
#define FANS_HAS_TRI 0
#define FANS_IRQ_TYPE NONE
#define FANS_RESET_VALUE 0

/*
 * Macros for device 'stepper_1_speed', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_1_SPEED_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_1_SPEED_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_1_SPEED_COMPONENT_NAME stepper_1_speed
#define STEPPER_1_SPEED_BASE 0x5000
#define STEPPER_1_SPEED_SPAN 16
#define STEPPER_1_SPEED_END 0x500f
#define STEPPER_1_SPEED_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_1_SPEED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_1_SPEED_CAPTURE 0
#define STEPPER_1_SPEED_DATA_WIDTH 32
#define STEPPER_1_SPEED_DO_TEST_BENCH_WIRING 0
#define STEPPER_1_SPEED_DRIVEN_SIM_VALUE 0
#define STEPPER_1_SPEED_EDGE_TYPE NONE
#define STEPPER_1_SPEED_FREQ 50000000
#define STEPPER_1_SPEED_HAS_IN 0
#define STEPPER_1_SPEED_HAS_OUT 1
#define STEPPER_1_SPEED_HAS_TRI 0
#define STEPPER_1_SPEED_IRQ_TYPE NONE
#define STEPPER_1_SPEED_RESET_VALUE 0

/*
 * Macros for device 'stepper_1_steps_in', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_1_STEPS_IN_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_1_STEPS_IN_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_1_STEPS_IN_COMPONENT_NAME stepper_1_steps_in
#define STEPPER_1_STEPS_IN_BASE 0x5020
#define STEPPER_1_STEPS_IN_SPAN 16
#define STEPPER_1_STEPS_IN_END 0x502f
#define STEPPER_1_STEPS_IN_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_1_STEPS_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_1_STEPS_IN_CAPTURE 0
#define STEPPER_1_STEPS_IN_DATA_WIDTH 32
#define STEPPER_1_STEPS_IN_DO_TEST_BENCH_WIRING 0
#define STEPPER_1_STEPS_IN_DRIVEN_SIM_VALUE 0
#define STEPPER_1_STEPS_IN_EDGE_TYPE NONE
#define STEPPER_1_STEPS_IN_FREQ 50000000
#define STEPPER_1_STEPS_IN_HAS_IN 1
#define STEPPER_1_STEPS_IN_HAS_OUT 0
#define STEPPER_1_STEPS_IN_HAS_TRI 0
#define STEPPER_1_STEPS_IN_IRQ_TYPE NONE
#define STEPPER_1_STEPS_IN_RESET_VALUE 0

/*
 * Macros for device 'stepper_2_speed', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_2_SPEED_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_2_SPEED_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_2_SPEED_COMPONENT_NAME stepper_2_speed
#define STEPPER_2_SPEED_BASE 0x5040
#define STEPPER_2_SPEED_SPAN 16
#define STEPPER_2_SPEED_END 0x504f
#define STEPPER_2_SPEED_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_2_SPEED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_2_SPEED_CAPTURE 0
#define STEPPER_2_SPEED_DATA_WIDTH 32
#define STEPPER_2_SPEED_DO_TEST_BENCH_WIRING 0
#define STEPPER_2_SPEED_DRIVEN_SIM_VALUE 0
#define STEPPER_2_SPEED_EDGE_TYPE NONE
#define STEPPER_2_SPEED_FREQ 50000000
#define STEPPER_2_SPEED_HAS_IN 0
#define STEPPER_2_SPEED_HAS_OUT 1
#define STEPPER_2_SPEED_HAS_TRI 0
#define STEPPER_2_SPEED_IRQ_TYPE NONE
#define STEPPER_2_SPEED_RESET_VALUE 0

/*
 * Macros for device 'stepper_2_steps_in', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_2_STEPS_IN_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_2_STEPS_IN_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_2_STEPS_IN_COMPONENT_NAME stepper_2_steps_in
#define STEPPER_2_STEPS_IN_BASE 0x5060
#define STEPPER_2_STEPS_IN_SPAN 16
#define STEPPER_2_STEPS_IN_END 0x506f
#define STEPPER_2_STEPS_IN_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_2_STEPS_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_2_STEPS_IN_CAPTURE 0
#define STEPPER_2_STEPS_IN_DATA_WIDTH 32
#define STEPPER_2_STEPS_IN_DO_TEST_BENCH_WIRING 0
#define STEPPER_2_STEPS_IN_DRIVEN_SIM_VALUE 0
#define STEPPER_2_STEPS_IN_EDGE_TYPE NONE
#define STEPPER_2_STEPS_IN_FREQ 50000000
#define STEPPER_2_STEPS_IN_HAS_IN 1
#define STEPPER_2_STEPS_IN_HAS_OUT 0
#define STEPPER_2_STEPS_IN_HAS_TRI 0
#define STEPPER_2_STEPS_IN_IRQ_TYPE NONE
#define STEPPER_2_STEPS_IN_RESET_VALUE 0

/*
 * Macros for device 'stepper_3_speed', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_3_SPEED_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_3_SPEED_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_3_SPEED_COMPONENT_NAME stepper_3_speed
#define STEPPER_3_SPEED_BASE 0x5080
#define STEPPER_3_SPEED_SPAN 16
#define STEPPER_3_SPEED_END 0x508f
#define STEPPER_3_SPEED_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_3_SPEED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_3_SPEED_CAPTURE 0
#define STEPPER_3_SPEED_DATA_WIDTH 32
#define STEPPER_3_SPEED_DO_TEST_BENCH_WIRING 0
#define STEPPER_3_SPEED_DRIVEN_SIM_VALUE 0
#define STEPPER_3_SPEED_EDGE_TYPE NONE
#define STEPPER_3_SPEED_FREQ 50000000
#define STEPPER_3_SPEED_HAS_IN 0
#define STEPPER_3_SPEED_HAS_OUT 1
#define STEPPER_3_SPEED_HAS_TRI 0
#define STEPPER_3_SPEED_IRQ_TYPE NONE
#define STEPPER_3_SPEED_RESET_VALUE 0

/*
 * Macros for device 'stepper_3_steps_in', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_3_STEPS_IN_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_3_STEPS_IN_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_3_STEPS_IN_COMPONENT_NAME stepper_3_steps_in
#define STEPPER_3_STEPS_IN_BASE 0x50a0
#define STEPPER_3_STEPS_IN_SPAN 16
#define STEPPER_3_STEPS_IN_END 0x50af
#define STEPPER_3_STEPS_IN_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_3_STEPS_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_3_STEPS_IN_CAPTURE 0
#define STEPPER_3_STEPS_IN_DATA_WIDTH 32
#define STEPPER_3_STEPS_IN_DO_TEST_BENCH_WIRING 0
#define STEPPER_3_STEPS_IN_DRIVEN_SIM_VALUE 0
#define STEPPER_3_STEPS_IN_EDGE_TYPE NONE
#define STEPPER_3_STEPS_IN_FREQ 50000000
#define STEPPER_3_STEPS_IN_HAS_IN 1
#define STEPPER_3_STEPS_IN_HAS_OUT 0
#define STEPPER_3_STEPS_IN_HAS_TRI 0
#define STEPPER_3_STEPS_IN_IRQ_TYPE NONE
#define STEPPER_3_STEPS_IN_RESET_VALUE 0

/*
 * Macros for device 'stepper_4_speed', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_4_SPEED_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_4_SPEED_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_4_SPEED_COMPONENT_NAME stepper_4_speed
#define STEPPER_4_SPEED_BASE 0x50c0
#define STEPPER_4_SPEED_SPAN 16
#define STEPPER_4_SPEED_END 0x50cf
#define STEPPER_4_SPEED_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_4_SPEED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_4_SPEED_CAPTURE 0
#define STEPPER_4_SPEED_DATA_WIDTH 32
#define STEPPER_4_SPEED_DO_TEST_BENCH_WIRING 0
#define STEPPER_4_SPEED_DRIVEN_SIM_VALUE 0
#define STEPPER_4_SPEED_EDGE_TYPE NONE
#define STEPPER_4_SPEED_FREQ 50000000
#define STEPPER_4_SPEED_HAS_IN 0
#define STEPPER_4_SPEED_HAS_OUT 1
#define STEPPER_4_SPEED_HAS_TRI 0
#define STEPPER_4_SPEED_IRQ_TYPE NONE
#define STEPPER_4_SPEED_RESET_VALUE 0

/*
 * Macros for device 'stepper_4_steps_in', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_4_STEPS_IN_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_4_STEPS_IN_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_4_STEPS_IN_COMPONENT_NAME stepper_4_steps_in
#define STEPPER_4_STEPS_IN_BASE 0x50e0
#define STEPPER_4_STEPS_IN_SPAN 16
#define STEPPER_4_STEPS_IN_END 0x50ef
#define STEPPER_4_STEPS_IN_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_4_STEPS_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_4_STEPS_IN_CAPTURE 0
#define STEPPER_4_STEPS_IN_DATA_WIDTH 32
#define STEPPER_4_STEPS_IN_DO_TEST_BENCH_WIRING 0
#define STEPPER_4_STEPS_IN_DRIVEN_SIM_VALUE 0
#define STEPPER_4_STEPS_IN_EDGE_TYPE NONE
#define STEPPER_4_STEPS_IN_FREQ 50000000
#define STEPPER_4_STEPS_IN_HAS_IN 1
#define STEPPER_4_STEPS_IN_HAS_OUT 0
#define STEPPER_4_STEPS_IN_HAS_TRI 0
#define STEPPER_4_STEPS_IN_IRQ_TYPE NONE
#define STEPPER_4_STEPS_IN_RESET_VALUE 0

/*
 * Macros for device 'stepper_1_steps_out', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_1_STEPS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_1_STEPS_OUT_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_1_STEPS_OUT_COMPONENT_NAME stepper_1_steps_out
#define STEPPER_1_STEPS_OUT_BASE 0x5100
#define STEPPER_1_STEPS_OUT_SPAN 16
#define STEPPER_1_STEPS_OUT_END 0x510f
#define STEPPER_1_STEPS_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_1_STEPS_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_1_STEPS_OUT_CAPTURE 0
#define STEPPER_1_STEPS_OUT_DATA_WIDTH 32
#define STEPPER_1_STEPS_OUT_DO_TEST_BENCH_WIRING 0
#define STEPPER_1_STEPS_OUT_DRIVEN_SIM_VALUE 0
#define STEPPER_1_STEPS_OUT_EDGE_TYPE NONE
#define STEPPER_1_STEPS_OUT_FREQ 50000000
#define STEPPER_1_STEPS_OUT_HAS_IN 0
#define STEPPER_1_STEPS_OUT_HAS_OUT 1
#define STEPPER_1_STEPS_OUT_HAS_TRI 0
#define STEPPER_1_STEPS_OUT_IRQ_TYPE NONE
#define STEPPER_1_STEPS_OUT_RESET_VALUE 0

/*
 * Macros for device 'stepper_2_steps_out', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_2_STEPS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_2_STEPS_OUT_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_2_STEPS_OUT_COMPONENT_NAME stepper_2_steps_out
#define STEPPER_2_STEPS_OUT_BASE 0x5120
#define STEPPER_2_STEPS_OUT_SPAN 16
#define STEPPER_2_STEPS_OUT_END 0x512f
#define STEPPER_2_STEPS_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_2_STEPS_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_2_STEPS_OUT_CAPTURE 0
#define STEPPER_2_STEPS_OUT_DATA_WIDTH 32
#define STEPPER_2_STEPS_OUT_DO_TEST_BENCH_WIRING 0
#define STEPPER_2_STEPS_OUT_DRIVEN_SIM_VALUE 0
#define STEPPER_2_STEPS_OUT_EDGE_TYPE NONE
#define STEPPER_2_STEPS_OUT_FREQ 50000000
#define STEPPER_2_STEPS_OUT_HAS_IN 0
#define STEPPER_2_STEPS_OUT_HAS_OUT 1
#define STEPPER_2_STEPS_OUT_HAS_TRI 0
#define STEPPER_2_STEPS_OUT_IRQ_TYPE NONE
#define STEPPER_2_STEPS_OUT_RESET_VALUE 0

/*
 * Macros for device 'stepper_3_steps_out', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_3_STEPS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_3_STEPS_OUT_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_3_STEPS_OUT_COMPONENT_NAME stepper_3_steps_out
#define STEPPER_3_STEPS_OUT_BASE 0x5140
#define STEPPER_3_STEPS_OUT_SPAN 16
#define STEPPER_3_STEPS_OUT_END 0x514f
#define STEPPER_3_STEPS_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_3_STEPS_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_3_STEPS_OUT_CAPTURE 0
#define STEPPER_3_STEPS_OUT_DATA_WIDTH 32
#define STEPPER_3_STEPS_OUT_DO_TEST_BENCH_WIRING 0
#define STEPPER_3_STEPS_OUT_DRIVEN_SIM_VALUE 0
#define STEPPER_3_STEPS_OUT_EDGE_TYPE NONE
#define STEPPER_3_STEPS_OUT_FREQ 50000000
#define STEPPER_3_STEPS_OUT_HAS_IN 0
#define STEPPER_3_STEPS_OUT_HAS_OUT 1
#define STEPPER_3_STEPS_OUT_HAS_TRI 0
#define STEPPER_3_STEPS_OUT_IRQ_TYPE NONE
#define STEPPER_3_STEPS_OUT_RESET_VALUE 0

/*
 * Macros for device 'stepper_4_steps_out', class 'altera_avalon_pio'
 * The macros are prefixed with 'STEPPER_4_STEPS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define STEPPER_4_STEPS_OUT_COMPONENT_TYPE altera_avalon_pio
#define STEPPER_4_STEPS_OUT_COMPONENT_NAME stepper_4_steps_out
#define STEPPER_4_STEPS_OUT_BASE 0x5160
#define STEPPER_4_STEPS_OUT_SPAN 16
#define STEPPER_4_STEPS_OUT_END 0x516f
#define STEPPER_4_STEPS_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define STEPPER_4_STEPS_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STEPPER_4_STEPS_OUT_CAPTURE 0
#define STEPPER_4_STEPS_OUT_DATA_WIDTH 32
#define STEPPER_4_STEPS_OUT_DO_TEST_BENCH_WIRING 0
#define STEPPER_4_STEPS_OUT_DRIVEN_SIM_VALUE 0
#define STEPPER_4_STEPS_OUT_EDGE_TYPE NONE
#define STEPPER_4_STEPS_OUT_FREQ 50000000
#define STEPPER_4_STEPS_OUT_HAS_IN 0
#define STEPPER_4_STEPS_OUT_HAS_OUT 1
#define STEPPER_4_STEPS_OUT_HAS_TRI 0
#define STEPPER_4_STEPS_OUT_IRQ_TYPE NONE
#define STEPPER_4_STEPS_OUT_RESET_VALUE 0

/*
 * Macros for device 'endstops', class 'altera_avalon_pio'
 * The macros are prefixed with 'ENDSTOPS_'.
 * The prefix is the slave descriptor.
 */
#define ENDSTOPS_COMPONENT_TYPE altera_avalon_pio
#define ENDSTOPS_COMPONENT_NAME endstops
#define ENDSTOPS_BASE 0x5200
#define ENDSTOPS_SPAN 16
#define ENDSTOPS_END 0x520f
#define ENDSTOPS_BIT_CLEARING_EDGE_REGISTER 0
#define ENDSTOPS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ENDSTOPS_CAPTURE 0
#define ENDSTOPS_DATA_WIDTH 6
#define ENDSTOPS_DO_TEST_BENCH_WIRING 0
#define ENDSTOPS_DRIVEN_SIM_VALUE 0
#define ENDSTOPS_EDGE_TYPE NONE
#define ENDSTOPS_FREQ 50000000
#define ENDSTOPS_HAS_IN 1
#define ENDSTOPS_HAS_OUT 0
#define ENDSTOPS_HAS_TRI 0
#define ENDSTOPS_IRQ_TYPE NONE
#define ENDSTOPS_RESET_VALUE 0

/*
 * Macros for device 'temp_bed', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP_BED_'.
 * The prefix is the slave descriptor.
 */
#define TEMP_BED_COMPONENT_TYPE altera_avalon_pio
#define TEMP_BED_COMPONENT_NAME temp_bed
#define TEMP_BED_BASE 0x6000
#define TEMP_BED_SPAN 16
#define TEMP_BED_END 0x600f
#define TEMP_BED_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_BED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_BED_CAPTURE 0
#define TEMP_BED_DATA_WIDTH 12
#define TEMP_BED_DO_TEST_BENCH_WIRING 0
#define TEMP_BED_DRIVEN_SIM_VALUE 0
#define TEMP_BED_EDGE_TYPE NONE
#define TEMP_BED_FREQ 50000000
#define TEMP_BED_HAS_IN 1
#define TEMP_BED_HAS_OUT 0
#define TEMP_BED_HAS_TRI 0
#define TEMP_BED_IRQ_TYPE NONE
#define TEMP_BED_RESET_VALUE 0

/*
 * Macros for device 'temp0', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP0_'.
 * The prefix is the slave descriptor.
 */
#define TEMP0_COMPONENT_TYPE altera_avalon_pio
#define TEMP0_COMPONENT_NAME temp0
#define TEMP0_BASE 0x6020
#define TEMP0_SPAN 16
#define TEMP0_END 0x602f
#define TEMP0_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP0_CAPTURE 0
#define TEMP0_DATA_WIDTH 12
#define TEMP0_DO_TEST_BENCH_WIRING 0
#define TEMP0_DRIVEN_SIM_VALUE 0
#define TEMP0_EDGE_TYPE NONE
#define TEMP0_FREQ 50000000
#define TEMP0_HAS_IN 1
#define TEMP0_HAS_OUT 0
#define TEMP0_HAS_TRI 0
#define TEMP0_IRQ_TYPE NONE
#define TEMP0_RESET_VALUE 0

/*
 * Macros for device 'temp1', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP1_'.
 * The prefix is the slave descriptor.
 */
#define TEMP1_COMPONENT_TYPE altera_avalon_pio
#define TEMP1_COMPONENT_NAME temp1
#define TEMP1_BASE 0x6040
#define TEMP1_SPAN 16
#define TEMP1_END 0x604f
#define TEMP1_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP1_CAPTURE 0
#define TEMP1_DATA_WIDTH 12
#define TEMP1_DO_TEST_BENCH_WIRING 0
#define TEMP1_DRIVEN_SIM_VALUE 0
#define TEMP1_EDGE_TYPE NONE
#define TEMP1_FREQ 50000000
#define TEMP1_HAS_IN 1
#define TEMP1_HAS_OUT 0
#define TEMP1_HAS_TRI 0
#define TEMP1_IRQ_TYPE NONE
#define TEMP1_RESET_VALUE 0

/*
 * Macros for device 'temp_bed_bottom', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP_BED_BOTTOM_'.
 * The prefix is the slave descriptor.
 */
#define TEMP_BED_BOTTOM_COMPONENT_TYPE altera_avalon_pio
#define TEMP_BED_BOTTOM_COMPONENT_NAME temp_bed_bottom
#define TEMP_BED_BOTTOM_BASE 0x6060
#define TEMP_BED_BOTTOM_SPAN 16
#define TEMP_BED_BOTTOM_END 0x606f
#define TEMP_BED_BOTTOM_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_BED_BOTTOM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_BED_BOTTOM_CAPTURE 0
#define TEMP_BED_BOTTOM_DATA_WIDTH 12
#define TEMP_BED_BOTTOM_DO_TEST_BENCH_WIRING 0
#define TEMP_BED_BOTTOM_DRIVEN_SIM_VALUE 0
#define TEMP_BED_BOTTOM_EDGE_TYPE NONE
#define TEMP_BED_BOTTOM_FREQ 50000000
#define TEMP_BED_BOTTOM_HAS_IN 0
#define TEMP_BED_BOTTOM_HAS_OUT 1
#define TEMP_BED_BOTTOM_HAS_TRI 0
#define TEMP_BED_BOTTOM_IRQ_TYPE NONE
#define TEMP_BED_BOTTOM_RESET_VALUE 0

/*
 * Macros for device 'temp_bed_upper', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP_BED_UPPER_'.
 * The prefix is the slave descriptor.
 */
#define TEMP_BED_UPPER_COMPONENT_TYPE altera_avalon_pio
#define TEMP_BED_UPPER_COMPONENT_NAME temp_bed_upper
#define TEMP_BED_UPPER_BASE 0x6080
#define TEMP_BED_UPPER_SPAN 16
#define TEMP_BED_UPPER_END 0x608f
#define TEMP_BED_UPPER_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_BED_UPPER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_BED_UPPER_CAPTURE 0
#define TEMP_BED_UPPER_DATA_WIDTH 12
#define TEMP_BED_UPPER_DO_TEST_BENCH_WIRING 0
#define TEMP_BED_UPPER_DRIVEN_SIM_VALUE 0
#define TEMP_BED_UPPER_EDGE_TYPE NONE
#define TEMP_BED_UPPER_FREQ 50000000
#define TEMP_BED_UPPER_HAS_IN 0
#define TEMP_BED_UPPER_HAS_OUT 1
#define TEMP_BED_UPPER_HAS_TRI 0
#define TEMP_BED_UPPER_IRQ_TYPE NONE
#define TEMP_BED_UPPER_RESET_VALUE 0

/*
 * Macros for device 'temp_e1_bottom', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP_E1_BOTTOM_'.
 * The prefix is the slave descriptor.
 */
#define TEMP_E1_BOTTOM_COMPONENT_TYPE altera_avalon_pio
#define TEMP_E1_BOTTOM_COMPONENT_NAME temp_e1_bottom
#define TEMP_E1_BOTTOM_BASE 0x60a0
#define TEMP_E1_BOTTOM_SPAN 16
#define TEMP_E1_BOTTOM_END 0x60af
#define TEMP_E1_BOTTOM_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_E1_BOTTOM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_E1_BOTTOM_CAPTURE 0
#define TEMP_E1_BOTTOM_DATA_WIDTH 12
#define TEMP_E1_BOTTOM_DO_TEST_BENCH_WIRING 0
#define TEMP_E1_BOTTOM_DRIVEN_SIM_VALUE 0
#define TEMP_E1_BOTTOM_EDGE_TYPE NONE
#define TEMP_E1_BOTTOM_FREQ 50000000
#define TEMP_E1_BOTTOM_HAS_IN 0
#define TEMP_E1_BOTTOM_HAS_OUT 1
#define TEMP_E1_BOTTOM_HAS_TRI 0
#define TEMP_E1_BOTTOM_IRQ_TYPE NONE
#define TEMP_E1_BOTTOM_RESET_VALUE 0

/*
 * Macros for device 'temp_e1_upper', class 'altera_avalon_pio'
 * The macros are prefixed with 'TEMP_E1_UPPER_'.
 * The prefix is the slave descriptor.
 */
#define TEMP_E1_UPPER_COMPONENT_TYPE altera_avalon_pio
#define TEMP_E1_UPPER_COMPONENT_NAME temp_e1_upper
#define TEMP_E1_UPPER_BASE 0x60c0
#define TEMP_E1_UPPER_SPAN 16
#define TEMP_E1_UPPER_END 0x60cf
#define TEMP_E1_UPPER_BIT_CLEARING_EDGE_REGISTER 0
#define TEMP_E1_UPPER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TEMP_E1_UPPER_CAPTURE 0
#define TEMP_E1_UPPER_DATA_WIDTH 12
#define TEMP_E1_UPPER_DO_TEST_BENCH_WIRING 0
#define TEMP_E1_UPPER_DRIVEN_SIM_VALUE 0
#define TEMP_E1_UPPER_EDGE_TYPE NONE
#define TEMP_E1_UPPER_FREQ 50000000
#define TEMP_E1_UPPER_HAS_IN 0
#define TEMP_E1_UPPER_HAS_OUT 1
#define TEMP_E1_UPPER_HAS_TRI 0
#define TEMP_E1_UPPER_IRQ_TYPE NONE
#define TEMP_E1_UPPER_RESET_VALUE 0

/*
 * Macros for device 'ILC', class 'interrupt_latency_counter'
 * The macros are prefixed with 'ILC_'.
 * The prefix is the slave descriptor.
 */
#define ILC_COMPONENT_TYPE interrupt_latency_counter
#define ILC_COMPONENT_NAME ILC
#define ILC_BASE 0x30000
#define ILC_SPAN 256
#define ILC_END 0x300ff


#endif /* _ALTERA_FPGA_ONLY_MASTER_H_ */
